# Generated by Selenium IDE
import time
import os
import json
from datetime import datetime as dt
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

downloads_dir = "/usr/public"
profile = webdriver.FirefoxProfile()
profile.set_preference('browser.download.folderList', 2) # custom location
profile.set_preference('browser.download.manager.showWhenStarting', False)
profile.set_preference('browser.download.dir', downloads_dir)
profile.set_preference('browser.helperApps.neverAsk.saveToDisk', 'text/csv')

driver = webdriver.Firefox(profile)
vars = {}
driver.get("http://dashboard.publichealth.lacounty.gov/covid19_surveillance_dashboard/")
driver.set_window_size(1099, 694)
driver.switch_to.frame(0)
driver.find_element(By.CSS_SELECTOR, "li:nth-child(5) span").click()
driver.find_element(By.ID, "download2").click()
time.sleep(5)
driver.find_element(By.CSS_SELECTOR, "li:nth-child(6) span").click()
driver.find_element(By.ID, "download4").click()
time.sleep(5)
driver.find_element(By.CSS_SELECTOR, "li:nth-child(7) span").click()
element = driver.find_element(By.ID, "download3").click()
time.sleep(5)
driver.find_element(By.CSS_SELECTOR, "li:nth-child(8) span").click()
driver.find_element(By.ID, "download5").click()
time.sleep(5)
driver.find_element(By.CSS_SELECTOR, "li:nth-child(9) span").click()
driver.find_element(By.ID, "download6").click()
time.sleep(5)
driver.quit()

timestamp = dt.now().strftime("%m-%d-%Y")
os.mkdir(timestamp)