# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGethtmltable():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_gethtmltable(self):
    # Test name: Get_html_table
    # Step # | name | target | value
    # 1 | open | /covid19_surveillance_dashboard/ | 
    self.driver.get("http://dashboard.publichealth.lacounty.gov/covid19_surveillance_dashboard/")
    # 2 | setWindowSize | 1920x1048 | 
    self.driver.set_window_size(1920, 1048)
    # 3 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 4 | click | css=li:nth-child(5) span | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(5) span").click()
    # 5 | click | name=DataTables_Table_0_length | 
    self.driver.find_element(By.NAME, "DataTables_Table_0_length").click()
    # 6 | select | name=DataTables_Table_0_length | label=All
    dropdown = self.driver.find_element(By.NAME, "DataTables_Table_0_length")
    dropdown.find_element(By.XPATH, "//option[. = 'All']").click()
    # 7 | click | css=option:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
    # 8 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 9 | click | css=li:nth-child(6) span | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6) span").click()
    # 10 | click | name=DataTables_Table_1_length | 
    self.driver.find_element(By.NAME, "DataTables_Table_1_length").click()
    # 11 | select | name=DataTables_Table_1_length | label=All
    dropdown = self.driver.find_element(By.NAME, "DataTables_Table_1_length")
    dropdown.find_element(By.XPATH, "//option[. = 'All']").click()
    # 12 | click | css=#DataTables_Table_1_length option:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, "#DataTables_Table_1_length option:nth-child(3)").click()
    # 13 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
  
